<?php

/**
 * @file
 * Primary module hooks for vactory_register module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function vactory_register_theme($existing, $type, $theme, $path) {
  return [
    'vactory_register_form' => [
      'template' => 'register',
      'variables' => [
        'form_register' => NULL,
      ],
    ],
  ];
}
